#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(f"numpy version is {np.__version__}")

numpy version is 1.23.5


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
print(f"Null vector of size 10 is {np.empty(10)}")

Null vector of size 10 is [4.64563401e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 1.29061927e+248 8.69923229e-043 1.74247955e-076 4.22487730e-090
 6.23080896e+174 2.59475292e-029]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
print(f"Memory size of any array is {np.empty(10).size * np.empty(10).itemsize}")

Memory size of any array is 80


In [ ]:
print(f"Memory size of any array is {np.empty(10).nbytes}")

Memory size of any array is 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
vector = np.zeros(10)
vector[4] = 1
print(f"Null vector of size 10 with fifth value is 1 is {vector}")

Null vector of size 10 with fifth value is 1 is [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
print(f"Vector with values ranging from 10 to 49 is {np.arange(start = 10,stop = 50)}")

Vector with values ranging from 10 to 49 is [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
np.random.seed(10)
vector = np.random.randint(0,10,5)
print(f"Vector before reverse is {vector}")
print(f"Vector after reverse is {vector[::-1]}")

Vector before reverse is [9 4 0 1 9]
Vector after reverse is [9 1 0 4 9]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
np.random.seed(10)
vector = np.arange(9).reshape(3,3)
print(f"3x3 Matrix with values ranging from 0 to 8 is \n {vector}")

3x3 Matrix with values ranging from 0 to 8 is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
vector = np.array([1,2,0,0,4,0])
print(f"Indices of non-zero element from {vector} is {vector.nonzero()}")

Indices of non-zero element from [1 2 0 0 4 0] is (array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
print(f"3x3 identity matrix is \n{np.eye(3)}")

3x3 identity matrix is 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
vector = np.random.randint(0,10,27).reshape(3,3,3)
print(f"3x3x3 array with random values is \n{vector}")

3x3x3 array with random values is 
[[[9 1 9]
  [4 2 6]
  [7 8 8]]

 [[9 2 0]
  [6 7 8]
  [1 7 1]]

 [[4 0 8]
  [5 4 7]
  [8 8 2]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
vector = np.random.randint(1,50,100).reshape(10,10)
min_value = vector.min()
max_value = vector.max()
print(f"10x10 array with random values is \n{vector}")
print(f"Minimum value is {min_value}")
print(f"Maximum value is {max_value}")

10x10 array with random values is 
[[24 42 32 38  7 47 26 34  8 10]
 [34  7 33 32 35 27 28  3 23  9]
 [22 40 29 18 28 40 34 34 30 19]
 [22 12  2 41 31  6 12 41 10 39]
 [30 20 10 12 32 30  4 25 47 49]
 [40 20  4 46  1 47  5  3 20  7]
 [48 28 39 37 37 10 44 15 49 31]
 [ 5 24 13 43 43 33 16 16 39 49]
 [38 35 25  4 14 28 48 48 14 12]
 [13 37  7 45 10 30 45 34 44 46]]
Minimum value is 1
Maximum value is 49


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
vector = np.random.randint(1,30,30).reshape(2,-1)
print(f"random vector is \n{vector}")
mean_vector = vector.mean()
print(f"Mean of random vector is {mean_vector}")

random vector is 
[[23 26  6 10  4 29 26 23 22 11 29  1 26 26 20]
 [ 2 13  9 19  2  8 20 24  3  4 28 27  3 22 16]]
Mean of random vector is 16.066666666666666


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a = np.ones((5,5))
a = np.pad(a,2)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
matrix = np.zeros((5,5))
count = 1
for row in range(1,5):
  for col in range(1,5):
    if row == col:
       matrix[row:row+1,col-1:col] = col
    count+=1
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix = np.zeros((8,8))
matrix[1::2,0::2]=1
matrix[0::2,1::2]=1
matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(f"The index (x,y,z) of 100th element is {np.unravel_index(99,(6,7,8))}")

The index (x,y,z) of 100th element is (1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
x = [[0,1],[1,0]]
matrix = np.tile(x,(4,4))
print(f"checkerboard 8x8 matrix using the tile function is \n{matrix}")

checkerboard 8x8 matrix using the tile function is 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
matrix = np.random.randint(1,11,25).reshape(5,5)
mean_value = matrix.mean()
std_value = matrix.std()
normalized_matrix = (matrix - mean_value) / std_value
print(f"Original matrix \n{matrix}")
print(f"Normalize matrix \n{normalized_matrix}")

Original matrix 
[[10  7 10  1  5]
 [ 8  9  3  9  7]
 [ 4  9  2  9  4]
 [ 3  4  1  7  3]
 [ 8  1  6  3  3]]
Normalize matrix 
[[ 1.53661702  0.52568477  1.53661702 -1.49617973 -0.14827006]
 [ 0.86266219  1.1996396  -0.8222249   1.1996396   0.52568477]
 [-0.48524748  1.1996396  -1.15920231  1.1996396  -0.48524748]
 [-0.8222249  -0.48524748 -1.49617973  0.52568477 -0.8222249 ]
 [ 0.86266219 -1.49617973  0.18870735 -0.8222249  -0.8222249 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
rgba_type = np.dtype([("R",np.uint8),("G",np.uint8),("B",np.uint8),("A",np.uint8)])
color = np.array([255,0,0,128],dtype = rgba_type)
print(f"Red: {color['R']}, Green: {color['G']}, Blue: {color['B']}, Alpha: {color['A']}")

Red: [255   0   0 128], Green: [255   0   0 128], Blue: [255   0   0 128], Alpha: [255   0   0 128]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix_A = np.random.randint(1,10,15).reshape(5,3)
matrix_B = np.random.randint(1,10,6).reshape(3,2)
print(f"Size of matrix A is {matrix_A.shape} And the matrix A is :\n{matrix_A}")
print(f"Size of matrix B is {matrix_B.shape} And the matrix B is :\n{matrix_B}")
print(f"Real matrix product is :\n{np.dot(matrix_A,matrix_B)}")

Size of matrix A is (5, 3) And the matrix A is :
[[5 4 3]
 [4 7 5]
 [2 1 9]
 [6 9 7]
 [4 7 1]]
Size of matrix B is (3, 2) And the matrix B is :
[[6 8]
 [1 9]
 [9 6]]
Real matrix product is :
[[ 61  94]
 [ 76 125]
 [ 94  79]
 [108 171]
 [ 40 101]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
vector = np.array([1,4,6,9,2,7,5,11,3,8])
print(f"The array is {vector}")
for i in range(vector.size):
  if 3 < vector[i] <8:
    vector[i]*=-1
print(f"The array after negate all elements which are between 3 and 8 is {vector}")

The array is [ 1  4  6  9  2  7  5 11  3  8]
The array after negate all elements which are between 3 and 8 is [ 1 -4 -6  9  2 -7 -5 11  3  8]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z         #legal
2 << Z >> 2  #legal
Z <- Z       #legal
1j*Z         #legal
Z/1/1        #legal
Z<Z>Z        #Not legal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
0.0

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
x = np.round([1.45, 1.50, 1.55])
print(x)
x = np.round([0.28, .50, .64],decimals=1)
print(x)

[1. 2. 2.]
[0.3 0.5 0.6]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
np.random.seed(10)
matrix_A = np.random.randint(1,11,9).reshape(3,3)
matrix_B = np.random.randint(1,11,9).reshape(3,3)
vector = np.array([])
for row in range(3):
  for col in range(3):
    if matrix_A[row,col] in matrix_B:
      if matrix_A[row,col] in vector:
        break
      else:
        vector = np.append(vector,matrix_A[row,col])
print(f"Matrix one is \n{matrix_A}")
print(f"Matrix two is \n{matrix_B}")
print(f"Common values between two arrays is {vector}")

Matrix one is 
[[10  5  1]
 [ 2 10  1]
 [ 2  9 10]]
Matrix two is 
[[1 9 7]
 [5 4 1]
 [5 7 9]]
Common values between two arrays is [5. 1. 9.]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
warn = np.seterr(all="ignore")
z = np.ones(5) / 0
print(f"vector divide by 0 without warning is {z}")

vector divide by 0 without warning is [inf inf inf inf inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
True

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64("today","D") - np.timedelta64(1,'D')
print(f"Date of yesterday is {yesterday}")
today = np.datetime64("today",'D')
print(f"Date of today is {today}")
tomorrow = np.datetime64("today",'D') + np.timedelta64(1,'D')
print(f"Date of tomorrow is {tomorrow}")

Date of yesterday is 2023-09-24
Date of today is 2023-09-25
Date of tomorrow is 2023-09-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
m = np.arange('2016-07' , '2016-08' , dtype = 'datetime64[D]')
print(f"All dates corresponding to the month of July 2016 \n {m}")

All dates corresponding to the month of July 2016 
 ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
A = A + B
A = A * (-A / 2)
print(f"Compute ((A+B)*(-A/2)) in place (without copy) is {A}")

Compute ((A+B)*(-A/2)) in place (without copy) is [-12.5 -24.5 -40.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
n = np.random.uniform(0,10,10)
np.random.seed(10)
print(f"Random array is \n {n}")
print(f"Method number one to extract the integer part of array is {n - n%1}")
print(f"Method number two to extract the integer part of array is {np.floor(n)}")
print(f"Method number three to extract the integer part of array is {n.astype(int)}")
print(f"Method number four to extract the integer part of array is {np.trunc(n)}")

Random array is 
 [7.71320643 0.20751949 6.33648235 7.48803883 4.98507012 2.24796646
 1.98062865 7.60530712 1.69110837 0.88339814]
Method number one to extract the integer part of array is [7. 0. 6. 7. 4. 2. 1. 7. 1. 0.]
Method number two to extract the integer part of array is [7. 0. 6. 7. 4. 2. 1. 7. 1. 0.]
Method number three to extract the integer part of array is [7 0 6 7 4 2 1 7 1 0]
Method number four to extract the integer part of array is [7. 0. 6. 7. 4. 2. 1. 7. 1. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
vector = np.array(range(5))
matrix = np.tile(vector,(5,1))
print(f"5x5 matrix with row ranging 0 to 4 is \n{matrix}")

5x5 matrix with row ranging 0 to 4 is 
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generator():
  vector = np.array([])
  for n in range(1,11):
    vector = np.append(vector,n)
  return vector
array = generator()
print(f"Array with generator function {array}")

Array with generator function [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
def generator():
  vector = np.random.randint(1,100,10)
  return vector
array = list(generator())
print(f"Array with random generator function {array}")

Array with random generator function [50, 52, 55, 78, 70, 14, 26, 14, 93, 87]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
vector = np.linspace(0, 1, 10).reshape(1,-1)
print(f"Vector of size 10 with values from 0 to 1 is \n{vector}")

Vector of size 10 with values from 0 to 1 is 
[[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
  0.66666667 0.77777778 0.88888889 1.        ]]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
np.random.seed(10)
vector = np.random.randint(1,50,10)
vector_sorted = np.sort(vector)
print(f"Vector before sorting is {vector}")
print(f"Vector after sorting is {vector_sorted}")

Vector before sorting is [10 37 16  1 29 26 30 49 30  9]
Vector after sorting is [ 1  9 10 16 26 29 30 30 37 49]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
z = np.arange(10)
sum = np.add.reduce(z)
print(f"Array is {z}")
print(f"Sum a small array faster than np.sum is np.add.reduce(array) {sum}")

Array is [0 1 2 3 4 5 6 7 8 9]
Sum a small array faster than np.sum is np.add.reduce(array) 45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([1, 2, 3, 4, 5])
if np.array_equal(A,B):
  print("Two random array A and B is equal")
else:
  print("Two random array A and B is Not equal")

Two random array A and B is equal


In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
f = 1
for row in range(3):
  for col in range(3):
    if A[row,col] != B[row,col]:
      f = 0
      break
if f == 1:
  print("Two random array A and B is equal")
else:
  print("Two random array A and B is Not equal")

Two random array A and B is equal


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
A = frozenset(np.array([1, 2, 3, 4, 5]))
print(f"Array can be read-only is {A}")
print(f"Array can be read-only without 'frozenset' is {list(A)}")

Array can be read-only is frozenset({1, 2, 3, 4, 5})
Array can be read-only without 'frozenset' is [1, 2, 3, 4, 5]


In [ ]:
A = np.array([1, 2, 3, 4, 5])
A.flags.writeable = False
print(f"Array can be read-only is {A}")

Array can be read-only is [1 2 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
np.random.seed(10)
matrix = np.random.random((10,2))
print(f"The random 10x2 matrix is \n {matrix} \n")
x = matrix[:,0]
y = matrix[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print()
print(t)

The random 10x2 matrix is 
 [[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]
 [0.19806286 0.76053071]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]
 [0.91777412 0.71457578]] 

[0.77159975 0.98092678 0.54684803 0.78589812 0.19079412 1.17417075
 0.51220748 1.01761535 0.77853862 1.16315428]

[0.02689795 0.86850441 0.42363518 1.31602818 0.48138948 0.94752207
 1.56308792 0.64590701 0.38429159 0.66155314]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
np.random.seed(10)
vector = np.random.randint(1,99,10)
print(f"Random vector of size 10 is {vector}")
max_value = vector.max()
max_index = np.argmax(vector)
vector[max_index] = 0
print(f"Random vector after remove maximum value '{max_value}' is {vector}")

Random vector of size 10 is [10 16 65 29 90 94 30  9 74  1]
Random vector after remove maximum value '94' is [10 16 65 29 90  0 30  9 74  1]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
array = np.zeros((5,5), [('x',float),('y',float)])
print(f"Array is \n{array}")
array['x'],array['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(f"Array is \n{array}")

Array is 
[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
Array is 
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
C = np.empty((len(X),len(Y)))
for i in range(len(X)):
  for j in range(len(Y)):
    C[i,j] = 1 / (X[i] - Y[j])
print(f"Cauchy Matrix is \n{C}")

Cauchy Matrix is 
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
int_type = [np.int8,np.int16,np.int32,np.int64]
for i in int_type:
  info = np.iinfo(i)
  print(f"{i}: Max = {info.max} , Min = {info.min}")

uint_type = [np.uint8,np.uint16,np.uint32,np.uint64]
for i in uint_type:
  info = np.iinfo(i)
  print(f"{i}: Max = {info.max} , Min = {info.min}")

float_type = [np.float16,np.float32,np.float64]
for i in float_type:
  info = np.finfo(i)
  print(f"{i}: Max = {info.max} , Min = {info.min}")

<class 'numpy.int8'>: Max = 127 , Min = -128
<class 'numpy.int16'>: Max = 32767 , Min = -32768
<class 'numpy.int32'>: Max = 2147483647 , Min = -2147483648
<class 'numpy.int64'>: Max = 9223372036854775807 , Min = -9223372036854775808
<class 'numpy.uint8'>: Max = 255 , Min = 0
<class 'numpy.uint16'>: Max = 65535 , Min = 0
<class 'numpy.uint32'>: Max = 4294967295 , Min = 0
<class 'numpy.uint64'>: Max = 18446744073709551615 , Min = 0
<class 'numpy.float16'>: Max = 65504.0 , Min = -65504.0
<class 'numpy.float32'>: Max = 3.4028234663852886e+38 , Min = -3.4028234663852886e+38
<class 'numpy.float64'>: Max = 1.7976931348623157e+308 , Min = -1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.random.seed(10)
array = np.random.randint(1,100,9).reshape(3,3)
print(f"Array is \n{array}")
for row in range(3):
  for col in range(3):
    print(array[row,col],end="  ")

Array is 
[[10 16 65]
 [29 90 94]
 [30  9 74]]
10  16  65  29  90  94  30  9  74  

In [ ]:
array = np.array([1, 2, 3, 4, 5])
print(f"Array is \n{array}")
for i in range(len(array)):
  print(array[i],end=" ")

Array is 
[1 2 3 4 5]
1 2 3 4 5 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
vector = np.array([1.2, 2.5, 3.8, 4.1, 5.7])
print(f"Vector is {vector}")
target = float(input("Enter your target : "))
difference_array = np.array([])
for i in range(len(vector)):
  difference = np.abs(target-vector[i])
  difference_array = np.append(difference_array,difference)
smallest_value_index = np.argmin(difference_array)
print(f"The closet value to your target '{target}' is {vector[smallest_value_index]} of index '{smallest_value_index}'")

Vector is [1.2 2.5 3.8 4.1 5.7]
Enter your target : 3.0
The closet value to your target '3.0' is 2.5 of index '1'


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
dtype = np.dtype([('position',[('x',float),('y',float)]) , ('color',[('r',int),('g',int),('b',int)])])
structured_array = np.array([((1.0, 2.0), (255, 0, 0)),
                             ((3.0, 4.0), (0, 255, 0)),
                             ((5.0, 6.0), (0, 0, 255))], dtype=dtype)
print(f"Structured Array : \n{structured_array}")
print(f"Position (x,y) at index 0 is : {structured_array['position'][0]}")
print(f"Color (r,g,b) at index 0 is : {structured_array['color'][0]}")

Structured Array : 
[((1., 2.), (255,   0,   0)) ((3., 4.), (  0, 255,   0))
 ((5., 6.), (  0,   0, 255))]
Position (x,y) at index 0 is : (1., 2.)
Color (r,g,b) at index 0 is : (255, 0, 0)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
vector = np.random.rand(100, 2)
n = vector.shape[0]
distances = np.zeros((n, n))
for i in range(n):
    for j in range(n):
       distances[i, j] = np.linalg.norm(vector[i] - vector[j])
print(f"Pairwise distances \n{distances}")

Pairwise distances 
[[0.         0.20424853 0.62572149 ... 0.70447177 0.17485561 0.11346428]
 [0.20424853 0.         0.58959645 ... 0.57852758 0.09731291 0.29786734]
 [0.62572149 0.58959645 0.         ... 0.30211407 0.50943054 0.59069253]
 ...
 [0.70447177 0.57852758 0.30211407 ... 0.         0.53926345 0.71818052]
 [0.17485561 0.09731291 0.50943054 ... 0.53926345 0.         0.23743441]
 [0.11346428 0.29786734 0.59069253 ... 0.71818052 0.23743441 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
array = np.array([1.5, 2.7, 3.3, 4.8],dtype = np.float32)
print(f"Array with float (32 bits) is {array}")
int_array = array.view(np.int32)
print(f"Array with int (32 bits) is {int_array}")

Array with float (32 bits) is [1.5 2.7 3.3 4.8]
Array with int (32 bits) is [1069547520 1076677837 1079194419 1083808154]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-78-7ba6b0e7042d>:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
array = np.array(range(1,10)).reshape(3,3)
print(f"Array is \n{array}")
for row in range(3):
  for col in range(3):
    position = (row,col)
    print(f"Index : {position} value : {array[row,col]}")

Array is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Index : (0, 0) value : 1
Index : (0, 1) value : 2
Index : (0, 2) value : 3
Index : (1, 0) value : 4
Index : (1, 1) value : 5
Index : (1, 2) value : 6
Index : (2, 0) value : 7
Index : (2, 1) value : 8
Index : (2, 2) value : 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma,mu = 1.0,0.0
g = np.exp(-((d-mu)**2/(2.0*sigma**2)))
print(f"2D Gaussian-like array is \n{g}")

2D Gaussian-like array is 
[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
from os import replace
n = 10
p = 3
z = np.zeros((n*n))
np.put(z,np.random.choice(range(n*n),p,replace=False),1)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0.]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
matrix = np.array(range(1,10)).reshape(3,3)
print(f"Original matrix : \n{matrix}")
mean_row = np.mean(matrix,axis=1)
print(f"Mean row is {mean_row}")
result = np.empty_like(matrix)
for row in range(3):
   result[row, :] = matrix[row, :] - mean_row[row]
print(f"Matrix with row means subtracted:\n{result}")

Original matrix : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean row is [2. 5. 8.]
Matrix with row means subtracted:
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
np.random.seed(10)
z = np.random.randint(0,10,(3,3))
print(f"Array before sorting is \n{z}\n")
sorted_data = sorted(z, key=lambda z: z[1])
print("Array after sorting is ")
for row in sorted_data:
    print(row)

Array before sorting is 
[[9 4 0]
 [1 9 0]
 [1 8 9]]

Array after sorting is 
[9 4 0]
[1 8 9]
[1 9 0]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
data = [
    [1, None, 3],
    [None, None, None],
    [4, None, 6]
]
f = 0
for col in range(len(data[0])):
  column_value = [row[col] for row in data]
  if all(value is None for value in column_values):
    f = 1
    break
if f == 1:
   print("The array has null columns.")
else:
   print("The array does not have null columns.")

The array has null columns.


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
vector = np.array([1, 3, 8, 12, 15])
print(f"Vector is {vector}")
target = int(input("Enter your target : "))
difference_array = np.array([])
for i in range(len(vector)):
  difference = np.abs(target-vector[i])
  difference_array = np.append(difference_array,difference)
smallest_value_index = np.argmin(difference_array)
print(f"The closet value to your target '{target}' is {vector[smallest_value_index]} of index '{smallest_value_index}'")

Vector is [ 1  3  8 12 15]
Enter your target : 7
The closet value to your target '7' is 8 of index '2'


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
np.random.seed(10)
matrix_A = np.random.randint(1,10,(1,3))
print(f"Matrix A is \n{matrix_A}")
np.random.seed(11)
matrix_B = np.random.randint(1,10,(3,1))
print(f"Matrix B is \n{matrix_B}")
matrix_B_copy = matrix_B.flatten()
matrix_sum = np.empty_like(matrix_A)
for row in range(1):
  for col in range(3):
    matrix_sum[row,col] = matrix_A[row,col] + matrix_B_copy[col]
print(f"Sum of two matrix with shape (1,3) is {matrix_sum}")
print(f"Sum of two matrix with shape (3,1) is \n{matrix_sum.reshape(3,1)}")

Matrix A is 
[[5 1 2]]
Matrix B is 
[[1]
 [2]
 [8]]
Sum of two matrix with shape (1,3) is [[ 6  3 10]]
Sum of two matrix with shape (3,1) is 
[[ 6]
 [ 3]
 [10]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class array_named:
  __name = None
  __array = np.array([])
  def __init__(self,name,data):
    self.__array = np.append(self.__array,data)
    self.__name = name
  def display(self):
    print(f"Array {self.__name} is {self.__array}")
array1 = array_named("Array one",[1,2,3,4,5])
array1.display()
array2 = array_named("Array two",[6,7,8,9,10])
array2.display()

Array Array one is [1. 2. 3. 4. 5.]
Array Array two is [ 6.  7.  8.  9. 10.]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
main_vector = np.array([1, 2, 3, 4, 5])
indices_to_add = np.array([1, 3, 1, 4])
result_vector = main_vector.copy()
new_indices = np.array([])
for i in range(len(indices_to_add)):
  if indices_to_add[i] in new_indices:
    continue
  else:
    new_indices = np.append(new_indices,indices_to_add[i])
new_indices_int = np.array(new_indices,dtype=np.int0)
new_indices_int = list(new_indices_int)

for i in new_indices_int:
  result_vector[i] +=1
print("Main Vector:", main_vector)
print("Indices Vector:", indices_to_add)
print("Result Vector:", result_vector)

Main Vector: [1 2 3 4 5]
Indices Vector: [1 3 1 4]
Result Vector: [1 3 3 5 6]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print("Vector X:", X)
print("Index List I:", I)
print("Result Array F:", F)

Vector X: [1, 2, 3, 4, 5, 6]
Index List I: [1, 3, 9, 3, 4, 1]
Result Array F: [0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
X = [9, 4, 5, 8, 10, 14]
I = [1, 3, 4]
F = [X[i] for i in I]
print("Vector X:", X)
print("Index List I:", I)
print("Result Array F:", F)

Vector X: [9, 4, 5, 8, 10, 14]
Index List I: [1, 3, 4]
Result Array F: [4, 8, 10]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w,h=4,4
image = np.random.randint(0,256,size=(w,h,3),dtype=np.uint8)
r_image = image.reshape(-1,3)
u_color = np.unique(r_image,axis=0)
n_u_color = u_color.shape[0]
print(f"The number of unique colors in the image is: {n_u_color}")

The number of unique colors in the image is: 16


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
arr = np.random.randint(0, 10, size=(4, 3, 2, 5))
sum = np.sum(arr, axis=(-2, -1))
print("Original Array Shape:", arr.shape)
print("Sum Over Last Two Axes Shape:", sum.shape)
print(f"Sum Over Last Two Axes:\n{sum}")

Original Array Shape: (4, 3, 2, 5)
Sum Over Last Two Axes Shape: (4, 3)
Sum Over Last Two Axes:
[[49 45 54]
 [49 49 44]
 [53 37 54]
 [49 34 31]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
S = np.array([0, 0, 1, 1, 2, 2, 2, 3, 3])
unique_indices = np.unique(S)
subset_means = [np.mean(D[S == idx]) for idx in unique_indices]
print("Vector D:", D)
print("Vector S:", S)
print("Subset Means:", subset_means)

Vector D: [1 2 3 4 5 6 7 8 9]
Vector S: [0 0 1 1 2 2 2 3 3]
Subset Means: [1.5, 3.5, 6.0, 8.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
D = np.diag(np.dot(A, B))
print(f"Diagonal of a dot product is {D}")

Diagonal of a dot product is [1.37664693 1.44282578 2.4650455  1.30748001 0.78018046]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
array = np.array([1, 2, 3, 4, 5])
array_zero = np.zeros(3,dtype=array.dtype)
result = []
for i in array:
  result.extend([i]+list(array_zero))
result

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
np.random.seed(10)
matrix_A = np.random.randint(0,11,(5,5,3))
matrix_B = np.random.randint(0,11,(5,5))
print(matrix_A*matrix_B[:,:,None])

[[[90 40  0]
  [ 9 81  0]
  [ 1 10  8]
  [18  0 20]
  [64 48 32]]

 [[27  0 36]
  [54 72 90]
  [ 5 40 20]
  [ 0  0  0]
  [10  6 18]]

 [[42 63  7]
  [27 12  6]
  [ 0  0  0]
  [40 32 36]
  [ 4  0 12]]

 [[ 0  0  0]
  [21  3 12]
  [30  0 24]
  [ 5  4  7]
  [16 16  4]]

 [[30 10 40]
  [72 54 54]
  [ 0  0  0]
  [ 0  0 60]
  [ 9  1  8]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
np.random.seed(20)
array = np.random.randint(1,11,(3,3))
print(f"Array before swapping \n{array}")
array_row_A = array[-1,:].copy()
array_row_B = array[-2,:].copy()
array[-1,:] = array_row_B
array[-2,:] = array_row_A
print(f"Array after swapping \n{array}")

Array before swapping 
[[ 4 10  5]
 [ 7  8  3]
 [ 1  7  9]]
Array after swapping 
[[ 4 10  5]
 [ 1  7  9]
 [ 7  8  3]]


In [ ]:
np.random.seed(20)
array = np.random.randint(1,11,(3,3))
print(f"Array before swapping \n{array}")
array[[0,1]] = array[[1,0]]
print(f"Array after swapping \n{array}")

Array before swapping 
[[ 4 10  5]
 [ 7  8  3]
 [ 1  7  9]]
Array after swapping 
[[ 7  8  3]
 [ 4 10  5]
 [ 1  7  9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
print(f"List of tuple\n{F}")
F = np.sort(F,axis=1)
G = F.view(dtype=[('p0',F.dtype),('p1',F.dtype)])
G = np.unique(G)
print(G)

List of tuple
[[ 8  6]
 [ 6 26]
 [26  8]
 [79 82]
 [82 78]
 [78 79]
 [10 33]
 [33 85]
 [85 10]
 [17 40]
 [40 82]
 [82 17]
 [42 60]
 [60 84]
 [84 42]
 [30 36]
 [36  8]
 [ 8 30]
 [48 19]
 [19 48]
 [48 48]
 [95 53]
 [53 10]
 [10 95]
 [38  9]
 [ 9 60]
 [60 38]
 [60 23]
 [23 52]
 [52 60]]
[( 6,  8) ( 6, 26) ( 8, 26) ( 8, 30) ( 8, 36) ( 9, 38) ( 9, 60) (10, 33)
 (10, 53) (10, 85) (10, 95) (17, 40) (17, 82) (19, 48) (23, 52) (23, 60)
 (30, 36) (33, 85) (38, 60) (40, 82) (42, 60) (42, 84) (48, 48) (52, 60)
 (53, 95) (60, 84) (78, 79) (78, 82) (79, 82)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
a = np.arange(20)
n = 3
ret = np.cumsum(a, dtype=float)
ret[n:] = ret[n:] - ret[:-n]
result = ret[n - 1:] / n
print(result)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
row_length = 3
num_rows = len(z) - row_length + 1
result = np.zeros((num_rows, row_length))
for i in range(num_rows):
    result[i, :] = z[i:i + row_length]
print(result)

[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]
 [5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
z = np.array([0,0,0,1,0,1,0,0])
x = np.array([-4,6,8,-7,-10,9])
print(f"Array before negate a boolean is {z}")
print(f"Array after negate a boolean is {np.logical_not(z, out=z)}")
print(f"Array before change sign is {x}")
print(f"Array after changesign is {np.negative(x, out=x)}")

Array before negate a boolean is [0 0 0 1 0 1 0 0]
Array after negate a boolean is [1 1 1 0 1 0 1 1]
Array before change sign is [ -4   6   8  -7 -10   9]
Array after changesign is [ 4 -6 -8  7 10 -9]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.array([[1, 1], [2, 2], [3, 3]])
P1 = np.array([[4, 1], [2, 3], [5, 6]])
p = np.array([2, 1])

distances = []

for i in range(len(P0)):
    v = P1[i] - P0[i]
    w = p - P0[i]
    projection = np.dot(w, v) / np.dot(v, v)
    perpendicular = w - projection * v
    distance = np.linalg.norm(perpendicular)
    distances.append(distance)

print(distances)


[0.0, 0.0, 0.2773500981126146]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.array([[1, 1], [2, 2], [3, 3]])
P1 = np.array([[4, 1], [2, 3], [5, 6]])
p = np.array([2, 1])

distances = []

for i in range(len(P0)):
    v = P1[i] - P0[i]
    w = p - P0[i]
    projection = np.dot(w, v) / np.dot(v, v)
    perpendicular = w - projection * v
    distance = np.linalg.norm(perpendicular)
    distances.append(distance)

print(distances)


[0.0, 0.0, 0.2773500981126146]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
def extract_centered_subarray(arr, shape, center, fill_value=0):
    half_shape = (shape[0] // 2, shape[1] // 2)
    row_start = max(center[0] - half_shape[0], 0)
    row_end = min(center[0] + half_shape[0] + 1, arr.shape[0])
    col_start = max(center[1] - half_shape[1], 0)
    col_end = min(center[1] + half_shape[1] + 1, arr.shape[1])
    subarray = np.full(shape, fill_value, dtype=arr.dtype)
    subarray[subarray.shape[0]//2-(center[0]-row_start):subarray.shape[0]//2-(center[0]-row_start)+(row_end-row_start),
             subarray.shape[1]//2-(center[1]-col_start):subarray.shape[1]//2-(center[1]-col_start)+(col_end-col_start)] = arr[row_start:row_end, col_start:col_end]
    return subarray

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15]])

shape = (3, 3)
center = (1, 2)
fill_value = 0

subarray = extract_centered_subarray(arr, shape, center, fill_value)
print(subarray)


In [ ]:
def extract(arr):
  new_arr = np.array([])
  new_arr = arr[:,1:]
  new_arr = new_arr[:,:-1]
  return new_arr
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15]])

print(extract(arr))

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
R = []
count = 4
for i in range(len(Z)):
  if count == 15:
    break
  else:
   R.append(Z[i:count])
   count +=1
R

[[1, 2, 3, 4],
 [2, 3, 4, 5],
 [3, 4, 5, 6],
 [4, 5, 6, 7],
 [5, 6, 7, 8],
 [6, 7, 8, 9],
 [7, 8, 9, 10],
 [8, 9, 10, 11],
 [9, 10, 11, 12],
 [10, 11, 12, 13],
 [11, 12, 13, 14]]

#### 82. Compute a matrix rank (★★★)

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
rank = np.linalg.matrix_rank(matrix)
print("Rank of the matrix:", rank)

Rank of the matrix: 2


#### 83. How to find the most frequent value in an array?

In [ ]:
matrix = np.array([1,3,5,5,4,8,6,5])
np.bincount(matrix).argmax()

5

In [ ]:
matrix = np.array([1, 3, 5, 5, 4, 8, 6, 5])
counts = np.bincount(matrix)
most_frequent_number = np.argmax(counts)
frequency = counts[most_frequent_number]
print("Most frequent number:", most_frequent_number)
print("Frequency:", frequency)

Most frequent number: 5
Frequency: 3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
matrix = np.random.randint(0, 100, (10, 10))
blooks = []
for i in range(8):
  for j in range(8):
    blooks.append(matrix[i:i+3,j:j+3])
count = 1
for block in blooks:
    print(f"Block {count}:\n{block}\n")
    count +=1

Block 1:
[[45  6 56]
 [75 11 31]
 [42  1  6]]

Block 2:
[[ 6 56 20]
 [11 31 80]
 [ 1  6 98]]

Block 3:
[[56 20 72]
 [31 80 24]
 [ 6 98 26]]

Block 4:
[[20 72 76]
 [80 24 68]
 [98 26 54]]

Block 5:
[[72 76 87]
 [24 68 51]
 [26 54 98]]

Block 6:
[[76 87 84]
 [68 51 69]
 [54 98 69]]

Block 7:
[[87 84 82]
 [51 69 89]
 [98 69 94]]

Block 8:
[[84 82 70]
 [69 89 69]
 [69 94 68]]

Block 9:
[[75 11 31]
 [42  1  6]
 [10 15 96]]

Block 10:
[[11 31 80]
 [ 1  6 98]
 [15 96 91]]

Block 11:
[[31 80 24]
 [ 6 98 26]
 [96 91  2]]

Block 12:
[[80 24 68]
 [98 26 54]
 [91  2 14]]

Block 13:
[[24 68 51]
 [26 54 98]
 [ 2 14 52]]

Block 14:
[[68 51 69]
 [54 98 69]
 [14 52 78]]

Block 15:
[[51 69 89]
 [98 69 94]
 [52 78  4]]

Block 16:
[[69 89 69]
 [69 94 68]
 [78  4 61]]

Block 17:
[[42  1  6]
 [10 15 96]
 [98 99  6]]

Block 18:
[[ 1  6 98]
 [15 96 91]
 [99  6 51]]

Block 19:
[[ 6 98 26]
 [96 91  2]
 [ 6 51 93]]

Block 20:
[[98 26 54]
 [91  2 14]
 [51 93 48]]

Block 21:
[[26 54 98]
 [ 2 14 52]
 [93 48 50]]

B

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p = 3
n = 4
matrices = []
vectors = []
for i in range(p):
    matrix = np.random.rand(n, n)
    matrices.append(matrix)
    vector = np.random.rand(n, 1)
    vectors.append(vector)

result = np.zeros((n, 1))

for i in range(p):
    for j in range(n):
        for k in range(n):
            result[j, 0] += matrices[i][j, k] * vectors[i][k, 0]
print(result)

[[3.41104378]
 [2.22065113]
 [2.56096987]
 [2.18498814]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
array_16x16 = np.arange(1, 257).reshape(16, 16)

block_sums = np.zeros((4,4), dtype=int)

for i in range(4):
    for j in range(4):
        block = array_16x16[i * 4:(i + 1) * 4, j * 4:(j + 1) * 4]
        block_sums[i, j] = np.sum(block)

print(f"Block Sums: \n{block_sums}")

Block Sums: 
[[ 424  488  552  616]
 [1448 1512 1576 1640]
 [2472 2536 2600 2664]
 [3496 3560 3624 3688]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):

    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
print(Z[np.argsort(Z)[-5:]])

[9995 9996 9997 9998 9999]


In [ ]:
Z = np.array([4,6,22,12,34,51,55,99])
print(Z[np.argsort(Z)[-5:]])

[22 34 51 55 99]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
from itertools import product

vector1 = [1, 2]
vector2 = ['A', 'B']
vector3 = [10, 20]

cartesian_product = list(product(vector1, vector2, vector3))

print(cartesian_product)


[(1, 'A', 10), (1, 'A', 20), (1, 'B', 10), (1, 'B', 20), (2, 'A', 10), (2, 'A', 20), (2, 'B', 10), (2, 'B', 20)]


In [ ]:
vector1 = [1, 2]
vector2 = ['A', 'B']
vector3 = [10, 20]

result = []

for i in range(2):
  for j in range(2):
    for k in range(2):
      result.append((vector1[i],vector2[j],vector3[k]))
print(result)

[(1, 'A', 10), (1, 'A', 20), (1, 'B', 10), (1, 'B', 20), (2, 'A', 10), (2, 'A', 20), (2, 'B', 10), (2, 'B', 20)]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
regular_array = np.array([(1, 'Alice', 25),
                           (2, 'Bob', 30),
                           (3, 'Charlie', 35)],
                          dtype=[('id', int), ('name', 'U10'), ('age', int)])

record_array = np.rec.fromarrays(regular_array.T, names=regular_array.dtype.names)

print(record_array)

((1, 'Alice', 25), (2, 'Bob', 30), (3, 'Charlie', 35))


In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
Z = np.array([2,3,4,5,6])
result1 = np.power(Z, 3)
print(result1)
result2 = Z ** 3
print(result2)
result3 = np.empty_like(Z)
for i in range(len(Z)):
    result3[i] = Z[i] **3
print(result3)

[  8  27  64 125 216]
[  8  27  64 125 216]
[  8  27  64 125 216]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
matrix = np.array([[2, 2, 3],
                   [1, 1, 1],
                   [4, 5, 6],
                   [2, 2, 2],
                   [7, 8, 9],
                   [1, 2, 3],
                   [1, 2, 3],
                   [5, 5, 5],
                   [3, 4, 3],
                   [1, 2, 2]])
U = matrix[matrix.max(axis=1) != matrix.min(axis=1) , : ]
print(U)             #as if

[[2 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [1 2 3]
 [3 4 3]
 [1 2 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
vector = np.array([5, 2, 10, 7], dtype=np.uint8)
binary_matrix = np.unpackbits(vector[:, np.newaxis], axis=1)
print(binary_matrix)

[[0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 0 1 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [1, 2, 3],
                  [7, 8, 9],
                  [4, 5, 6]])
unique_rows = np.unique(array, axis=0)
print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
sum_result = np.einsum('i->', A)
elementwise_product = np.einsum('i,i->i', A, B)
inner_product = np.einsum('i,i', A, B)
outer_product = np.einsum('i,j->ij', A, B)

print("Summation:", sum_result)
print("Element-wise Multiplication:", elementwise_product)
print("Inner Product (Dot Product):", inner_product)
print("Outer Product:", outer_product)

Summation: 6
Element-wise Multiplication: [ 4 10 18]
Inner Product (Dot Product): 32
Outer Product: [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
X = np.array([0, 2, 4, 7, 9, 11, 13, 16, 18, 20])
Y = np.array([0, 1, 3, 6, 8, 10, 11, 13, 14, 15])

path_length = np.sum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))

num_samples = 20

step_size = path_length / (num_samples - 1)

sampled_points = np.zeros((num_samples, 2))

sampled_points[0] = [X[0], Y[0]]
current_position = 0

for i in range(1, num_samples):
    remaining_distance = i * step_size

    while current_position < len(X) - 1:
        dx = X[current_position + 1] - X[current_position]
        dy = Y[current_position + 1] - Y[current_position]
        segment_length = np.sqrt(dx**2 + dy**2)

        if remaining_distance <= segment_length:
            sampled_points[i] = [X[current_position] + remaining_distance * (dx / segment_length),
                                 Y[current_position] + remaining_distance * (dy / segment_length)]
            break
        else:
            remaining_distance -= segment_length
            current_position += 1

print(sampled_points)

[[ 0.          0.        ]
 [ 1.18995277  0.59497639]
 [ 2.3003417   1.3003417 ]
 [ 4.8222208   3.8222208 ]
 [ 7.76296107  6.76296107]
 [11.89011961 10.4450598 ]
 [17.91481354 13.95740677]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.array([[1, 2, 3],
              [2, 3, 0],
              [0, 1, 4],
              [1, 1, 3],
              [0, 4, 1]])
n = 5
valid_rows = []
for row in X:
    if np.sum(row) == n:
        valid_rows.append(row)

selected_rows = np.array(valid_rows)

print(selected_rows)

[[2 3 0]
 [0 1 4]
 [1 1 3]
 [0 4 1]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.12922975  0.27963554]
